### ISSUE TITLE
How to refer (from TraCES to Dillmann, in the same entry) and PoS in case of a book of the Bible (ex.: entry Dāwit)

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#325] opened 2019-04-12 11:01 UTC
Dear Pietro and dear all,

I have two questions:
1) do we have a standard way to refer from TraCES to Dillmann within the same entry? Is this 
Internal Reference {DiL.} meant also for that?

Have a look to this entry: 
https://betamasaheft.eu/Dillmann/lemma/L928bb64b41094ffcba04412c5c4b09e3

In Dillmann there was already the entry for dāwit: "1) n. pr. regis Israelitarum David" and "2) psalterium , liber biblicus".
To this I added a TraCES "Sense", with Bibliographical informations from the Chronicle of Amda Seyon of Marrassini,  also with the two "dāwit" already in Dillmann: 1) the king, as example of a masculine personal name, and the book. I provisionally used, to refer to the Dillmann Sense: for the first Dāwit "(= above, Dillmann 1)", for the second "(= above, Dillmann 2)". 

2) Which label, as  PoS, do we use in case of a book of the Bible?

Again, for Dāwit, I wrote "book of the Bible".

Thank you,
Vita

**Comment by abausi** [comment] 2019-04-12 11:20
No, Vitagrazia, we cannot distinguish to which specific sub-meaning among the various meanings of one entry we refer. With the lexical annotation you can only select an entry and that's it.

**Comment by PietroLiuzzo** [comment] 2019-04-12 12:00
for the internal references in the app, we will keep for the moment the issue open and use the syntax used here by Vitagrazia. When we will have a decent amount I will modify the scripts to tranform this in a link to the correct sense. the user hovering on the reference (which will also be printed differently) will see the block of the sense highlighted

**Comment by abausi** [comment] 2019-04-12 12:01
I do not exactly understand the point of the syntax: can you explain better?

**Comment by PietroLiuzzo** [comment] 2019-04-12 12:03
The requirement in the first part of this question is to univocally refer to one of the senses in another meaning, which we can do, and is useful for the reader especially for longer examples.

**Comment by MagdaKrzyz** [comment] 2019-04-12 12:04
But maybe instead of writing the whole phrase, we can use an abbre. "ad.
sense 1" or sth. to this effect.

pt., 12 kwi 2019 o 14:00 Pietro Liuzzo <notifications@github.com>
napisał(a):

**Comment by abausi** [comment] 2019-04-12 12:04
How can we distinguish within an entry, that has only one ID? how can we locate the meaning that is actually meant?

**Comment by PietroLiuzzo** [comment] 2019-04-12 12:05
each sense inside each meaning also has its id in the XML. during the transformation I can generate unique ids also for the exposed HTML / PDF so that links can be created referring to those anchors. This is not difficult. I would only like to wait until there are a few cases, two do not really justify the effort at the moment, the users gets the same information simply reading.

**Comment by PietroLiuzzo** [comment] 2019-04-12 12:07
@MagdaKrzyz sure, the wording proposed by Vitagrazia is also fine, and can be used to match this information

**Comment by abausi** [comment] 2019-04-12 12:11
I think we are movign towards a completely other level of work and complexity, i.e. the additional annotation of XML files exported from (TraCES) GeTa: am I right?

**Comment by eu-genia** [comment] 2019-04-12 12:15
@abausi: we are talking here about Dillmann Lexicon online, not GeTa. Vitagrazia simply suggested linking between TraCES-added English-language meanings and Dillmann's Latin meanings. (I know it was not clear)

**Comment by abausi** [comment] 2019-04-12 12:18
Thank you, now I understand: I was misled by the use of "PoS", i.e. a typical category we come across in GeTa. So all this has only to do with a new occurrence of a known meaning within the Dillmann lexicon

**Comment by eu-genia** [comment] 2019-04-12 12:19
Yes, correct, simply establishing a clear correspondence inside the dictionary entry
(I had the same initial problem with the understanding, of course there are no additional PoS for submeanings - but Pietro got it right immediately, and that's what matters!)

**Comment by vitagrazia81** [comment] 2019-04-15 09:43
Thank you Pietro for the answer and to all of you, and sorry if I was not clear and immediately understood
(in General I would not write something about Geta here, in this repository, where we usually write issues for  the Dillmann online :-)).

About the first  and more crucial question, yes, it is exactely how Pietro said, that is, about how  to "univocally refer" (never used "linking"), also simply in terms of terminology, from a sense to another sense in a Dillmann online entry , or to other sub meanings. An internal reference between senses would be indeed, as Pietro said, useful and more needed when the sense, or the sub meaning, has several examples or when we will have several senses (in difference languages and sources). I asked simply if the reference (or "syntax" ) which I used in the traCES sense for Dawit, i.d. "(= above, Dillmannn 1)/(=above, Dillmann 2,), is for the moment acceptable or not, or whether there was already a standard way or a way already used by another editor.

**Comment by abausi** [comment] 2019-04-15 10:01
Dear Vitagrazia,

many thanks, all is fine.

Il 15.04.2019 10:43, vitagrazia81 ha scritto:

**Comment by eu-genia** [comment] 2019-08-21 10:37
Dear @MagdaKrzyz - if you are not satisfied with this issue above please feel free to document here your proposed solution, so that everyone involved can see. As far as I see it, it is not really important which syntax you use to link the meanings
(TraCES meaning 5 = above, Dillmann 1 as suggested earlier, or 
TraCES meaning 5 ad. sense 1.b, or in whichever other wording) 
as long as the same sequence is always used; this will then be used by @PietroLiuzzo to transform the text into the link, so that the users won't be confused:

> the user hovering on the reference (which will also be printed differently) will see the block of the sense highlighted

Since @vitagrazia81 was the first to offer a code, for the moment the best idea would be to follow her lead and be consistent, unless there is a true problem with the syntax offered.

**Comment by MagdaKrzyz** [comment] 2019-09-03 15:48
Dear All, 
new entries that have been introduced into Dillmann’s Lexicon (DL) need to be better organized if we want the dictionary to be user friendly. From my discussion with Pietro (30.08.) it turns out that he cannot offer any better visualization unless there is already some structure imposed on the data. That means, unless we manually indicate that a given string is within meaning 1) and the next within meaning 2) the programme won’t know. The same holds for cross-references, additions to existing DL (sub)meanings etc. The issue is broader in scope and that what Vita proposed should be seen in a wider context. The question that she raised is v. important but the solution is not optimal. So far it has only been implemented in one case. 
The first question to be addressed is how we perceive the TraCES (TR) part. As a totally independent part, which would mean that we start enumerating with “1)” for each newly introduced meaning of the same headword? Or do we conceive the TR part as a continuation of DL? In that case we would continue DL’s numbering and so each time a new meaning is added, it will be marked as the next sequential item, continuing from DL’s list?  For instance, if DL gives three numbered entries, the first TR entry will get number 4. 
I am for the second solution and the reasons for it will be seen in what follows. 
I want to stress here that because most coders are not well-versed in Latin and because Dillmann’s dictionary shows some formatting inconsistencies here and there, it would be better if we don’t commit ourselves to hierarchy within the TR entries and to total consistency in nesting. That is, any additions that we make will be assigned a number but without any implications about how it fits into Dillmann’s preexisting hierarchy of meanings. 
ACHTUNG! Note that the examples provided below have been structured tentatively for the sake of presentation.
Basically, 5 types of additions are made:
a)	a new entry (clear and so won’t be mentioned further)
b)	a new meaning
c)	a new submeaning to Dillmann’s meaning
d)	a new example for an existing meaning
e)	cross-reference 
Some organization is needed for points b) - e).  
1)	We add a new meaning/meanings to a headword which already has at least 2 meanings.  Do we count our new meaning as the subsequent one, say 3), or do we start counting from 1)? As mentioned before, I am for continuing DL’s numbering. 
Here are examples: 
የውሀት፡ https://betamasaheft.eu/Dillmann/lemma/Lb3bf85ee9eea4b76a9a92a5b04ccc14d. (with one meaning added)
https://betamasaheft.eu/Dillmann/lemma/L08617a7ea8ca4f6695392667610a01e6 
ግብአት፡ https://betamasaheft.eu/Dillmann/lemma/L952aa1b9546b41dfac1402fcecbaa33d (with two meanings added)
https://betamasaheft.eu/Dillmann/lemma/L57b10f54a15e4ab9810cd59bcfca0f21 (with 3 meanings added)
2)	In DL there is an entry with just one meaning (with or without submeanings). If we add a new meaning, (how) do we number it? If we continue DL’s numbering we can add “1)” to DL’s part and mark the TR meaning as “2)”. If we don’t want to tamper with DL we can simply mark the TR meaning as “2)” and DL’s meaning should be tacitly understood as “1)”. 
Here is an ex. with nesting: 
ሐቀላዊ፡ https://betamasaheft.eu/Dillmann/lemma/Lca452d220c3046dc9f7c102e1f60ee72
Here are examples without nesting:
ጸብእ፡ https://betamasaheft.eu/Dillmann/lemma/L8afa14032fc8432ebf27e11b639df660
 https://betamasaheft.eu/Dillmann/lemma/L7557903fdfd042f6b1ff81dd569d5f21 
3)	If we want to add info on one of DL’s (sub)meanings, how do we refer to this additional info? We could place the info in situ, i.e. within DL’s part but with an appropriate TraCES tag. Alternatively, we could refer to DL’s meaning with something like “ad2)” (if we want to refer to the 2. meaning). This “ad2)” would be of the same shape and position as any listed meaning. Our convention could be that first we list references to DL’s meanings and only then new meanings and finally cross-references. 
This point is especially important because there is a number of compounds and collocations. Dillmann usually lists them as submeanings of a certain meaning and labels them either as a), b)… etc or α), β) … etc. (depends on how many nested levels there are). He seems not to be consistent and sometimes one can find a collocation listed under a), b) and sometimes simply added after as an integral part of a fairly long first meaning. 
In this entry, the new collocation should be listed under DL’s 1) or 2) (see below for a comment).
https://betamasaheft.eu/Dillmann/lemma/L44c0fe3b85064f5390af25d24bc46aac 
In the following entries, the new compound should be listed under DL’s 2)
https://betamasaheft.eu/Dillmann/lemma/Lf0feecf0e34940ec80c9a8fa9a1bbd0f 
https://betamasaheft.eu/Dillmann/lemma/L3fea5842d4f34768ab02bac45e4f0584 
In the following case I would suggest to add “ad. 4” and then indicate two submeanings: a) and b). 
https://betamasaheft.eu/Dillmann/lemma/L49035195ba954b20939e04bf0d9cceb24) 
4)	If DL has only one meaning to which we want to refer (and so there is no ‘1)’), we could implicitly treat this single meaning as “1)” and refer to it as “ad1)”. This would seem to be the clearest way. 
https://betamasaheft.eu/Dillmann/lemma/L65a9a45cdf5f4b9581622a9df884bd29 
https://betamasaheft.eu/Dillmann/lemma/L1886d37d0afa46879c0a31ae8d0b8814 
5)	Cross-references 
Cross-references of the headword (not of a particular meaning!) could be separated from the meanings by establishing a section “Cross-references”. Each cross-reference would start with a bullet point, as in the following example:
ባሕር፡ https://betamasaheft.eu/Dillmann/lemma/L015fb11cc2a74db1816932c3e52e2874 
Cross-references would be listed after LESLAU but perhaps before ETYMOLOGY
6)	Now etymology is given in the following way:
https://betamasaheft.eu/Dillmann/lemma/L6eb58c893ab04d0d9bca6dd0c6c2bcd0
https://betamasaheft.eu/Dillmann/lemma/L4f03661d6115452d8f61e7de09c1c936
https://betamasaheft.eu/Dillmann/lemma/Ld845416cc7224062a147dad81364e547
The labels “amh”, “tg” etc. previously given to some entries will be removed. 
Unless there is an authority to whom I can appeal, the etymological section will consist simply of cognates, with no diachronic analysis. Instead of “etymology” it may be more accurate to call this section “Comparative data”. 
7)	Verb-noun collocations
Where should they be listed, under the verb or rather under the noun? Perhaps the best principle would be a pragmatic one. That means, if the noun is more salient (and the verb is rather general, eg. “take”, “make”, “do”), the collocation will be under the noun, and vice versa. They are always cross-referenced. 
Here are two examples:
https://betamasaheft.eu/Dillmann/lemma/L44c0fe3b85064f5390af25d24bc46aac
https://betamasaheft.eu/Dillmann/lemma/L5e41e709981a464cb61961fa944b1690 
8)	Even though I am in principle for the second solution, i.e. for continuing Dillmann’s enumeration, sometimes it could make trouble for the coder. The point is that Dillmann belongs to the type of lexicographers known as ‘splitters’ ( in contrast to the other type known as ‘lumpers’) and one may have problems to decide which of the DL’s meanings one should refer to (when one adds some info to the existing meaning). Because Dillmann distinguishes so many meanings, one has to know Latin very well to be able to decide which of the meaningsis the “right” one. Translating into Latin by means of Latin Word Study Tool is not always helpful because one gets decontextualized synonyms. Here is an example: 
https://betamasaheft.eu/Dillmann/lemma/L44c0fe3b85064f5390af25d24bc46aac
The question is whether በልዐ፡ መሐላ፡ should be referred to meaning 1) or 2), both translated as ‘oath’. We would have to study more closely Dillmann’s examples to understand the difference between them. The cop-out could be that we would try to make references whenever it is possible but if we are not sure we could simply number the entry with a subsequent number without any reference to an existing DL meaning. Even if the entry we are entering is a collocation, and not a new meaning, we would give it number 1) (and not a), b) etc.). 
m

**Comment by eu-genia** [comment] 2019-09-05 10:09
I agree that clear guidelines are needed; I am not sure that in some cases I see the problem.
1. I would restart from 1. The meanings should have the numbering Dillmann 1-2-3 TraCES 1-2-3 etc. - this is perfectly sufficient for the computer to distinguish them. We cannot expect, also for the reasons specified under 8, that one from the very beginning decides whether the meanings are completely new or not.
This would also save us the necessity to renumber if new meanings for some reason are introduced to boxes above. 
E.g. one discovers by chance that the Dillmann box for some technical error misses a meaning number 3, then all TraCES meanings would have to be renumbered which could lead to even more confusion if there are boxes after TraCES (see also 3 below).

2. If for Pietro it is OK to introduce "implicit" numbering number 1 does not have to be specified when there is only one meaning, either in Dillmann or in TraCES or in any other future section. BTW in the example you provide https://betamasaheft.eu/Dillmann/lemma/L44c0fe3b85064f5390af25d24bc46aac there is no number for TraCES and it is OK - either we number everything, or we do not number when there is one of a subset only.
If this is a technical challenge I would introduce 1 everywhere.

3. As we already discussed above, there is no difference, from the point of view of user friendliness, or of computer programming, which string you use to refer, as long as we are consistent.
There is no difference between e.g. "ad2" and "= Dillmann 2" (or Dillmann 2a, or Dillmann 3c, whichever you need to refer to). I would be for the more extended string (i.e. = Dillmann 2) in case we have a third box (let's say Leslau, even if for now it is within TraCES - once Dasha's results are mapped Leslau will become a separate box) and want to link from Leslau to TraCES to Dillmann too. Then it could be "= TraCES 1" "= Dillmann 3c" in the same line. So I remain with Vitagrazia's suggestion. (without maybe "above", as one could potentially change the alignment of the boxes)

4. see 2 above.

5. there may be a better way to structure the "cross-references" (other than bulleting)

6. Probably OK for the structure but the words must still be tagged as the specific language they are in, esp. in case we want in some distant future to link the dictionary e.g. to a dictionary or corpus of Amharic /Tigrinya etc.

7. OK for me

8. See 1 above. then the problem does not exist. you can link e.g. from TraCES 2 to "= Dillmann 3a" or "= Dillmann 3g" 
As long as the "link" string is always consistent and the numbering is stable there shall be no problem for Pietro to convert these strings to "true" links.

**Comment by MagdaKrzyz** [comment] 2019-09-05 15:31
1.	The computer, as I understand, cannot distinguish the meanings unless WE distinguish them, and the meanings are to be distinguished for the user, after all.
“We cannot expect, also for the reasons specified under 8, that one from the very beginning decides whether the meanings are completely new or not.” – my point 8) calls for caution and shows a way out of a potential problem that a coder may come across. I think it is worth trying to pin down the meaning of a new item and integrate it into the lexicon in the least confusing way. Restarting from 1) is perhaps not a bad idea but it does not show how the TR part corresponds to the DL part. 
“E.g. one discovers by chance that the Dillmann box for some technical error misses a meaning number 3, then all TraCES meanings would have to be renumbered which could lead to even more confusion if there are boxes after TraCES” – there are here and there mistakes in nesting but of a rather different nature. E.g. meaning 2) is embedded in 1). 
2.	Your suggestion is not clear to me. I will try react to it but maybe wrongly.
 There is some sense to add 1) to DL only if we decide to continue DL’s numbering. We should not do that automatically though but whenever such a need arises. In case we want to restart from 1), we will not care if DL has any enumerating at all.
3.	Here I meant something slightly different. “ad2)” etc. could be coded in the same way as “1)”, “2)” etc., so ENCODED, not written after the appropriate number. In case there are new meanings and references to DL’s meanings, we enter first references and then new meanings. 
But I support the longer string in case it brings sth. for the user (see 8.) 
As for Leslau, is it planned for the future to do so? It would be good first to try it out with some entries because it may be an arduous task. 
4.	-
5.	Cross- references: feel free to propose a different way than bulleting. 
6.	Each word is tagged according to its language. 
7.	–
8.	If this brings sth, useful for the user, why not.

**Comment by MagdaKrzyz** [comment] 2019-09-05 17:18
Here is an example that may help us to decide which organizing structure is more convinient (for the users and the coders). 
Look at this entry, following the structure: we continue DL's counting
https://betamasaheft.eu/Dillmann/lemma/L08617a7ea8ca4f6695392667610a01e6

Here is the same entry organized in the other way: we start counting from 1). How to indicate that the first meaning is the g) submeaning of 1)? Or do we disregard this aspect? Note that here the sign of equality "=" is not appropriate:
1) (Dillmann 1) castleen, fortressen, palaceen ወበጺሖ፡ ጉባኤ፡ አተወ፡ ውስተ፡ ማኅፈዱ፡ ዘአዳም፡ ስነ፡ ኅንፄሃ፡ ወንኩር፡ አርአያሃ፡ ‘ Arrivé à Gubāʾē, il entra dans son château, de belle construction et d’un extérieur admirablefr’ Conti Rossini 1907, 117 l. 20-22 (ed.) , Conti Rossini 1907, 133 l. 27-29 (tr.) , ካዕበ፡ ኃረይዋ፡ ለይእቲ፡ ምድር፡ ከመ፡ ይኩን፡ ህየ፡ ከተማ፡ ንጉሥ፡ ወይትሐነጽ፡ ባቲ፡ ማኅፈደ፡ ንጉሥ፡ ‘ On choisit aussi ce pays, pour y établir la résidence du roi, et y bàtir un château pour le roifr’ Conti Rossini 1907, 137 l. 29-31 (ed.) , Conti Rossini 1907, 156 l. 29-31 (tr.) , ወወረደ፡ ምድረ፡ አደል፡ ወአውዓየ፡ አህጉሪሆሙ፡ በእሳት፡ ወአንሀለ፡ ማኅፈዳቲሆሙ። ‘ scese nella terra di Adal, e incendiò col fuoco le loro città, e distrusse le loro fortezzeit’ Conti Rossini 1894, 7 l. 17-19 (ed); 18 l. 5-6 (tr.) 
2) sign of the zodiacen በሳድስ፡ ሱባዔ፡ እምሱባዔያተ፡ ጾም፡ ቅድስት፡ እንዘ፡ ሀሎ፡ ፀሐይ፡ በማኅፈደ፡ ተውር፡ በመክብብ፡ ፲መዓርግ፡ እመዓርግ፡ ዐቢያን፡ during the sixth week of the weeks of the the Holy lent, when the sun is in the sign of the Zodiac of Taurus in the circle of ten degrees among the great degreesen Solomon Gebreyes 2019, 57 § 107 (ed.) , Solomon Gebreyes 2019, 33 § 107 (tr.)

**Comment by abausi** [comment] 2019-09-05 17:22
Good that this discussion goes on. I do not have time to look at it in 
detail now; I will do as soon as possible.

Il 05.09.2019 19:18, MagdaKrzyz ha scritto:

**Comment by eu-genia** [comment] 2019-09-06 08:10
1. Of course the meanings should be distinguished, but as long as they are numbered (and they are, also in Dillmann), they are distinguished. Everything which is numbered and indented can be seen as possessing its own XML-ID. Which the numbers are is relevant for us, not for the computer, and we should choose the mode which is the easiest to follow for everyone, not just for one person. It has no difference whether the linking is TraCES 3 = Dillmann 1 or TraCES 1 = Dillmann 1. 
On the other hand, the suggestion to keep one continuous numbering would mean that under TraCES if you decide that you continue a Dillmann meaning 2 you should assign number 2, and not 1 (if it is the first paragraph) and not 5 (if there are already 4 under Dillmann). I am strongly against this.
Each box should start numbering from 1, and relations be established between the meanings via linking, whichever the wording is. I am strongly in favour of Vitagrazia's suggestion which works for all cases, whether main meanings or submeanings, as long as they are numbered properly.

2. Introducing vs non-introducing 1 - this depends once again on whether @PietroLiuzzo says that the computer understands that the only unnumbered meaning has number 1. Otherwise the linking (e.g. TraCES has 3 meanings, Dillmann has 1 unnumbered one, and you want to link TraCES 2 to Dillmann unnumbered (=1)) would not work. You need an ID (= number) to be able to refer to entities. You should start thinking digitally. This is not a paper dictionary. It has a different functionality.

3. The string ad2 and the string = Dillmann 2 make no difference for computing in the sense of encoding. Once the rule has been decided upon and Pietro has modified the script, whichever string decided upon would equal to encoding. For the machine it makes no difference which rule to learn, as long as there is a rule.

**Comment by eu-genia** [comment] 2019-09-06 08:17
In your example https://betamasaheft.eu/Dillmann/lemma/L08617a7ea8ca4f6695392667610a01e6
it is fully sufficient to indicate (= Dillmann 1), as it is not a new submeaning, it is rather the general meaning as given above, or more closely the submeaning 1c. (You could say = Dillmann 1c if you want to be so very specific)

The example in mahfad, however, confirms me in the conviction that we must introduce "1" for single meanings, as otherwise once you start adding new meanings in TraCES or elsewhere the whole nesting breaks (1g and 2 should not be at the same level, and now they are)

**Comment by vitagrazia81** [comment] 2019-09-06 12:37
Dear @MagdaKrzyz, 
concerning point 1, I agree with @eu-genia: TraCES  numbering should be indipendent from the Dillmann`s one. It should start from 1 and not be a continuation of Dillmann.  This would avoid, e.g., problem of confusion to the editor and to the user. We would also avoid situation, such as your last example, where Dillmann does not have any number. In the example which you give, the entry for the word "mahfad", Dillmann in fact does not give any number to the main and single meaning "Turris", but only sub letters with sub meanings which specify the type  of "Turris". If we follow your suggestion and we leave this  TraCES entry as it is now, we  should first somehow introduce number 1), with the main meaning "Turris" (followed by the latin letters as submeanings), within the  Dillmann sense, and only after, we could continue, in TraCES, the Dillmann numbering. Then, as also @eu-genia said, g) and 2), how they are now in TraCES, should not be at the same level. For the first meaning of TraCES,  "castleen, fortressen, palaceen"..., I would not even use the letter g), since the meaning "castleen, fortressen, palaceen" is similar and/or related to Dillmann c). For me a better solution would be to restart in TraCES an indipendent numbering; in the entry I  would  write: “1) castleen, fortressen, palaceen…” and “2) sign of the zodiacen..."; in the meaning 1), after the translations of the word into English, I would give the internal reference to Dillmann c).

**Comment by abausi** [comment] 2019-09-09 14:08
Thank you all for your proposals, suggestions, and remarks, which 
witness of the engagement and thoughtfullness of your work. I tried know 
to follow the discussion more in detail and there is decisione to be 
taken now, of which I have to take the responsibility. I am also in 
favour of what suggested by Vitagrazia and Zhenia, for the main reason 
of linearity of workflow. The fact that we start from Dillmann, does not 
mean that we have reproduce its typography; we have other ways to 
indicate precisely what is meant and for establishing equivalences.

It remains now to make consistent the entries inserted so far; and for 
the future it would be good if we discuss in detail this, before having 
too many adjustments to do later.

Il 06.09.2019 14:37, vitagrazia81 ha scritto:

**Comment by MagdaKrzyz** [comment] 2019-09-09 16:06
Dear All,

unless Susanne presents a different point of view, you have decided on the option of restarting the numbering (and all consequences thereof) and I accept that. 
As Vita is responsible for the guidlines, could you please add all these new rules? It would be perfect if you attend to the eight points that were mentioned in my first message. There are links to useful examples but if you need more I suggest you look for them in the last 70 entries that I introduced.
It would be important for me to know how to number, if at all, compounds and collocationes. 
All the best
Magda

**Comment by vitagrazia81** [comment] 2019-09-10 09:31
Dear @MagdaKrzyz
I will insert the point of the numbering of the meanings in TraCES -point on which there was the final decision-, in the Guidelines, it is not a problem. 
Anyway, I am not responsible of the Guidelines at all. Everybody is free to modify and update it, as it was done so far. It was done that the one who proposed some new rules wrote them in the document. Many of the last updates of the Guidelines, in fact, as you know, came from you.

**Comment by MagdaKrzyz** [comment] 2019-09-10 10:24
I am sorry Vita, I thought you are responsible for the guidlines and i just
replaced you when you were on your maternity leave. Good, so please insert
what you feel up to. What should we do with the remaining points?

vitagrazia81 <notifications@github.com> schrieb am Di., 10. Sep. 2019,
12:31:

**Comment by PietroLiuzzo** [comment] 2019-09-13 07:46
sure, no problem, these changes will however not affect any of the existing data and their visualization, so I was only thinking that it would have been better not to interrupt your work plans, and you would have been able to test. I will proceed locally only and wait next week for the live app.

**Comment by MagdaKrzyz** [comment] 2019-09-13 09:40
Dear Pietro,
I understand, so please go ahead with your plans.


Pietro Liuzzo <notifications@github.com> schrieb am Fr., 13. Sep. 2019,
10:46:

**Comment by PietroLiuzzo** [comment] 2019-09-18 14:47
eventually the syntax I picked is lighter, simply #D2a for example. on click, it will bring you to the correct meaning, on hovering will add to its box a shadow to make it stand out.

**Closed** 2019-09-18 14:50 UTC
Labels: data
